# options for analysis running
run:
  concurrency: 1
  deadline: 5m

  # include test files or not
  tests: true

# output configuration options
output:
  # colored-line-number|line-number|json|tab|checkstyle
  format: colored-line-number

# all available settings of specific linters
linters-settings:
  lll:
    line-length: 190

linters:
  enable:
    - errcheck
    - unused
    - dupl
    - gosimple
    - goconst
    - maligned
    - misspell
    - unparam
    - nakedret
    - golint
    - megacheck
    - deadcode
    - varcheck
    - structcheck
    - unconvert
    - ineffassign
    - gofmt
    - lll
    - gosec
    - interfacer
    - govet
    - gosimple
